# Site settings
url: "http://127.0.0.1:43110" # the base hostname & protocol for your site
baseurl: "/1FPSdChfmaAjMMUgoYLxAYHTDS46gnvmUw/"
# Use master instead of beta for the files dir, so that we minimize duplicate
# peer effort
files_url: "http://127.0.0.1:43110/1EZSUprqJQph9JwKg3gAJtiNs899vatZTo"
